import { 
  User, Factory, SubscriptionPlan, Product, RawMaterial, RawMaterialPurchase, 
  ProductionBatch, StockTransaction, Employee, AttendanceRecord, WageSlip, 
  Customer, Vendor, SaleOrder, Invoice, Expense, Payment, NotificationItem, 
  AuditLogItem 
} from '@/types';
import { generateId } from '@/utils/formatters';

const STORAGE_KEY = 'brickflow_erp_db_v1';

export interface DatabaseSchema {
  users: User[];
  factories: Factory[];
  plans: SubscriptionPlan[];
  products: Product[];
  rawMaterials: RawMaterial[];
  purchases: RawMaterialPurchase[];
  productionBatches: ProductionBatch[];
  stockTransactions: StockTransaction[];
  employees: Employee[];
  attendance: AttendanceRecord[];
  wageSlips: WageSlip[];
  customers: Customer[];
  vendors: Vendor[];
  saleOrders: SaleOrder[];
  invoices: Invoice[];
  expenses: Expense[];
  payments: Payment[];
  notifications: NotificationItem[];
  auditLogs: AuditLogItem[];
}

const SEED_DATA: DatabaseSchema = {
  plans: [
    {
      id: 'plan_trial',
      name: 'Free Trial',
      price: 0,
      billingCycle: 'monthly',
      maxUsers: 2,
      maxMonthlyProduction: '50,000 Bricks',
      features: ['Single Factory', 'Raw Material & Stock Tracking', 'Basic Sales & Invoices', '14-Day Free Access'],
      status: 'active',
    },
    {
      id: 'plan_basic',
      name: 'Basic Plant',
      price: 2499,
      billingCycle: 'monthly',
      maxUsers: 5,
      maxMonthlyProduction: '2,50,000 Bricks',
      features: ['Single Machine/Kiln Line', 'Raw Material Purchases', 'Stock & Inventory Ledger', 'Daily Attendance & Labour Wages', 'GST Invoicing & PDF', 'WhatsApp Order Sharing', 'Standard Reports'],
      status: 'active',
    },
    {
      id: 'plan_standard',
      name: 'Standard Pro',
      price: 4999,
      billingCycle: 'monthly',
      maxUsers: 15,
      maxMonthlyProduction: '10,00,000 Bricks',
      isPopular: true,
      features: ['Multi-Machine & Multi-Kiln Chambers', 'Complete Automated Stock Balancing', 'Piece-Rate & Daily Wage Payroll', 'Customer Receivables & Aging', 'Vendor Payables & Purchase Ledgers', 'Advanced P&L and Cost Per Brick Analysis', 'SMS/WhatsApp Payment Reminders', 'Audit Logs & User Roles'],
      status: 'active',
    },
    {
      id: 'plan_enterprise',
      name: 'Enterprise Multi-Plant',
      price: 9999,
      billingCycle: 'monthly',
      maxUsers: 50,
      maxMonthlyProduction: 'Unlimited Bricks',
      features: ['Multi-Factory Operations', 'Dedicated Account Manager', 'Custom ERP Integrations', 'Weighbridge Automation Ready', 'Priority 24/7 Phone Support', 'Automated Daily Backup & Cloud Archival'],
      status: 'active',
    },
  ],

  factories: [
    {
      id: 'fact_01',
      name: 'Shree Ram Brick Industries',
      code: 'SRB-01',
      ownerName: 'Rajesh Sharma',
      phone: '+91 85006 93113',
      email: 'info@shreerambricks.com',
      address: 'Plot 45-B, Industrial Estate, Hadapsar',
      city: 'Pune',
      state: 'Maharashtra',
      pincode: '411028',
      gstNumber: '27AABCS1429B1Z8',
      factoryType: 'Fly Ash Brick',
      employeesCount: '25-50 Workers',
      dailyCapacity: '35,000 Bricks / Day',
      mainProducts: ['4 Inch Fly Ash Brick', '6 Inch Fly Ash Brick', '8 Inch Hollow Block', 'Paver Blocks'],
      planId: 'plan_standard',
      subscriptionStatus: 'active',
      subscriptionExpiry: '2027-12-31',
      createdAt: '2025-01-15T09:00:00Z',
      bankDetails: {
        bankName: 'HDFC Bank Ltd',
        accountNumber: '50200088991122',
        ifscCode: 'HDFC0001234',
        branch: 'Hadapsar Branch, Pune',
        upiId: 'shreerambricks@okhdfcbank',
      },
    },
    {
      id: 'fact_02',
      name: 'Bharat Clay & Kiln Works',
      code: 'BCW-02',
      ownerName: 'Manoj Kumar Gupta',
      phone: '+91 94150 98765',
      email: 'contact@bharatclayworks.com',
      address: 'NH-2 Bypass, Near Ramnagar Toll Plaza',
      city: 'Varanasi',
      state: 'Uttar Pradesh',
      pincode: '221008',
      gstNumber: '09AACFB8892K1Z4',
      factoryType: 'Clay / Red Brick',
      employeesCount: '50-100 Workers',
      dailyCapacity: '50,000 Bricks / Day',
      mainProducts: ['Red Clay Fired Bricks', 'High-Strength Zig-Zag Bricks'],
      planId: 'plan_basic',
      subscriptionStatus: 'active',
      subscriptionExpiry: '2026-11-20',
      createdAt: '2025-03-10T10:30:00Z',
    },
    {
      id: 'fact_03',
      name: 'Mahalaxmi Pavers & Precast',
      code: 'MPS-03',
      ownerName: 'Kiritbhai Patel',
      phone: '+91 98795 44332',
      email: 'sales@mahalaxmipavers.com',
      address: 'GIDC Industrial Area, Sachin',
      city: 'Surat',
      state: 'Gujarat',
      pincode: '394230',
      gstNumber: '24AAECM7721P1Z1',
      factoryType: 'Paver Block & Tiles',
      employeesCount: '15-25 Workers',
      dailyCapacity: '20,000 Blocks / Day',
      mainProducts: ['Interlocking Pavers', 'Solid Precast Blocks'],
      planId: 'plan_trial',
      subscriptionStatus: 'trial',
      subscriptionExpiry: '2026-09-18',
      createdAt: '2026-08-20T11:00:00Z',
    },
  ],

  users: [
    {
      id: 'usr_admin',
      email: 'admin@brickflow.io',
      fullName: 'Vikramaditya Rao (Super Admin)',
      phone: '+91 99887 76655',
      role: 'super_admin',
      status: 'active',
      createdAt: '2025-01-01T00:00:00Z',
    },
    {
      id: 'usr_owner',
      email: 'owner@shreerambricks.com',
      fullName: 'Rajesh Sharma (Owner)',
      phone: '+91 98220 12345',
      role: 'factory_owner',
      factoryId: 'fact_01',
      status: 'active',
      createdAt: '2025-01-15T09:00:00Z',
    },
    {
      id: 'usr_super',
      email: 'admin@patterns.cloud',
      fullName: 'Super Admin (Patterns Cloud)',
      phone: '+91 85006 93113',
      role: 'super_admin',
      status: 'active',
      createdAt: '2025-01-01T00:00:00Z',
    },
  ],

  products: [
    {
      id: 'prod_01',
      factoryId: 'fact_01',
      name: '4 Inch Fly Ash Cement Brick',
      code: 'FAB-4IN',
      category: 'Fly Ash Brick',
      unit: 'Pcs',
      hsnCode: '681599',
      sellingPrice: 4.80,
      costPrice: 3.10,
      minimumStock: 15000,
      currentStock: 48500,
      dimensions: '9 x 4 x 3 Inch',
      status: 'active',
      description: 'High compressive strength 4-inch fly ash brick ideal for partition walls and residential construction.',
      createdAt: '2025-01-16T10:00:00Z',
    },
    {
      id: 'prod_02',
      factoryId: 'fact_01',
      name: '6 Inch Fly Ash Cement Brick',
      code: 'FAB-6IN',
      category: 'Fly Ash Brick',
      unit: 'Pcs',
      hsnCode: '681599',
      sellingPrice: 6.90,
      costPrice: 4.40,
      minimumStock: 10000,
      currentStock: 32400,
      dimensions: '9 x 6 x 3 Inch',
      status: 'active',
      description: 'Heavy duty 6-inch load bearing fly ash brick.',
      createdAt: '2025-01-16T10:00:00Z',
    },
    {
      id: 'prod_03',
      factoryId: 'fact_01',
      name: '8 Inch Concrete Hollow Block',
      code: 'CHB-8IN',
      category: 'Hollow Block',
      unit: 'Pcs',
      hsnCode: '681011',
      sellingPrice: 34.00,
      costPrice: 21.50,
      minimumStock: 3000,
      currentStock: 7800,
      dimensions: '16 x 8 x 8 Inch',
      status: 'active',
      description: 'Lightweight thermal insulated hollow concrete masonry blocks for boundary walls & high-rise frames.',
      createdAt: '2025-01-20T10:00:00Z',
    },
    {
      id: 'prod_04',
      factoryId: 'fact_01',
      name: 'Zig-Zag Paver Block 80mm Heavy Duty',
      code: 'PAV-80ZZ',
      category: 'Paver Block',
      unit: 'Pcs',
      hsnCode: '681019',
      sellingPrice: 15.50,
      costPrice: 9.80,
      minimumStock: 8000,
      currentStock: 19500,
      dimensions: '80mm Thickness (M-40 Grade)',
      status: 'active',
      description: 'M40 grade interlocking zig-zag pavers for industrial driveways, petrol pumps and container yards.',
      createdAt: '2025-01-22T10:00:00Z',
    },
    {
      id: 'prod_05',
      factoryId: 'fact_01',
      name: 'Red Clay Kiln Fired Brick (Standard)',
      code: 'RCK-STD',
      category: 'Red Clay Brick',
      unit: 'Pcs',
      hsnCode: '690410',
      sellingPrice: 8.50,
      costPrice: 5.40,
      minimumStock: 20000,
      currentStock: 62000,
      dimensions: '9 x 4.25 x 2.75 Inch',
      status: 'active',
      description: 'Traditional coal-fired chamber kiln red clay bricks with uniform ringing sound and rich red color.',
      createdAt: '2025-01-25T10:00:00Z',
    },
  ],

  rawMaterials: [
    {
      id: 'rm_01',
      factoryId: 'fact_01',
      name: 'Grade 53 OPC Cement (UltraTech / ACC)',
      code: 'RM-CEM53',
      unit: 'Bags',
      minimumStock: 150,
      currentStock: 480,
      averageUnitCost: 345,
      totalPurchased: 4200,
      totalConsumed: 3720,
      status: 'active',
      createdAt: '2025-01-16T10:00:00Z',
    },
    {
      id: 'rm_02',
      factoryId: 'fact_01',
      name: 'Thermal Fly Ash (Grade F dry powder)',
      code: 'RM-FLYASH',
      unit: 'Ton',
      minimumStock: 40,
      currentStock: 92.5,
      averageUnitCost: 680,
      totalPurchased: 850,
      totalConsumed: 757.5,
      status: 'active',
      createdAt: '2025-01-16T10:00:00Z',
    },
    {
      id: 'rm_03',
      factoryId: 'fact_01',
      name: 'Crushed Stone Dust (0-4mm aggregate)',
      code: 'RM-SDUST',
      unit: 'Ton',
      minimumStock: 50,
      currentStock: 145.0,
      averageUnitCost: 490,
      totalPurchased: 1200,
      totalConsumed: 1055,
      status: 'active',
      createdAt: '2025-01-16T10:00:00Z',
    },
    {
      id: 'rm_04',
      factoryId: 'fact_01',
      name: 'River Washed Sand (M-Sand)',
      code: 'RM-RSAND',
      unit: 'Brass',
      minimumStock: 12,
      currentStock: 28.0,
      averageUnitCost: 4200,
      totalPurchased: 180,
      totalConsumed: 152,
      status: 'active',
      createdAt: '2025-01-16T10:00:00Z',
    },
    {
      id: 'rm_05',
      factoryId: 'fact_01',
      name: 'Calcined Gypsum Powder',
      code: 'RM-GYP',
      unit: 'Bags',
      minimumStock: 30,
      currentStock: 22, // Low stock! Below 30
      averageUnitCost: 240,
      totalPurchased: 350,
      totalConsumed: 328,
      status: 'active',
      createdAt: '2025-01-16T10:00:00Z',
    },
    {
      id: 'rm_06',
      factoryId: 'fact_01',
      name: 'High CV Boiler Coal (Kiln Fuel)',
      code: 'RM-COAL',
      unit: 'Ton',
      minimumStock: 20,
      currentStock: 42.0,
      averageUnitCost: 7200,
      totalPurchased: 240,
      totalConsumed: 198,
      status: 'active',
      createdAt: '2025-01-16T10:00:00Z',
    },
  ],

  purchases: [
    {
      id: 'pur_01',
      factoryId: 'fact_01',
      purchaseDate: '2026-08-28',
      materialId: 'rm_01',
      materialName: 'Grade 53 OPC Cement (UltraTech / ACC)',
      quantity: 300,
      unit: 'Bags',
      vendorId: 'ven_01',
      vendorName: 'UltraTech Cement Authorized Depot',
      vendorPhone: '+91 98221 00112',
      truckNumber: 'MH-12-Q-9944',
      driverName: 'Sanjay Yadav',
      driverPhone: '+91 97654 32100',
      rate: 345,
      totalAmount: 103500,
      paidAmount: 70000,
      pendingAmount: 33500,
      paymentStatus: 'partial',
      paymentMode: 'bank_transfer',
      notes: 'Delivered batch invoice #UT-9921',
      createdAt: '2026-08-28T14:30:00Z',
    },
    {
      id: 'pur_02',
      factoryId: 'fact_01',
      purchaseDate: '2026-08-30',
      materialId: 'rm_02',
      materialName: 'Thermal Fly Ash (Grade F dry powder)',
      quantity: 45,
      unit: 'Ton',
      vendorId: 'ven_02',
      vendorName: 'Maha Thermal Ash Logistics',
      vendorPhone: '+91 99230 44556',
      truckNumber: 'MH-14-EA-7712',
      driverName: 'Kailash Rathore',
      rate: 680,
      totalAmount: 30600,
      paidAmount: 30600,
      pendingAmount: 0,
      paymentStatus: 'paid',
      paymentMode: 'upi',
      notes: 'Full payment via GPay on unloading',
      createdAt: '2026-08-30T16:00:00Z',
    },
    {
      id: 'pur_03',
      factoryId: 'fact_01',
      purchaseDate: '2026-09-01',
      materialId: 'rm_03',
      materialName: 'Crushed Stone Dust (0-4mm aggregate)',
      quantity: 60,
      unit: 'Ton',
      vendorId: 'ven_03',
      vendorName: 'Shree Krishna Stone Crushers',
      vendorPhone: '+91 98810 33221',
      truckNumber: 'MH-12-AB-5541',
      driverName: 'Popat Jadhav',
      rate: 490,
      totalAmount: 29400,
      paidAmount: 15000,
      pendingAmount: 14400,
      paymentStatus: 'partial',
      paymentMode: 'cheque',
      notes: 'Chq #409181 drawn on SBI',
      createdAt: '2026-09-01T11:20:00Z',
    },
  ],

  productionBatches: [
    {
      id: 'batch_01',
      factoryId: 'fact_01',
      batchCode: 'BAT-2026-0891',
      productionDate: '2026-09-01',
      productId: 'prod_01',
      productName: '4 Inch Fly Ash Cement Brick',
      targetQuantity: 15000,
      outputQuantity: 14750,
      damagedQuantity: 250,
      unit: 'Pcs',
      machineLine: 'Automatic Hydraulic Line 1',
      kilnChamber: 'Yard Curing Area #2',
      supervisorName: 'Dinesh Patil',
      mixProportion: '1 Part Cement : 5 Parts Fly Ash : 3 Parts Stone Dust',
      materialsUsed: [
        { materialId: 'rm_01', materialName: 'Grade 53 OPC Cement', quantity: 42, unit: 'Bags' },
        { materialId: 'rm_02', materialName: 'Thermal Fly Ash', quantity: 9.5, unit: 'Ton' },
        { materialId: 'rm_03', materialName: 'Crushed Stone Dust', quantity: 6.2, unit: 'Ton' },
      ],
      workersCount: 14,
      startTime: '08:00 AM',
      endTime: '05:30 PM',
      status: 'completed',
      qualityGrade: 'A Grade',
      remarks: 'Smooth edge finish, standard compression achieved.',
      createdAt: '2026-09-01T08:00:00Z',
    },
    {
      id: 'batch_02',
      factoryId: 'fact_01',
      batchCode: 'BAT-2026-0892',
      productionDate: '2026-09-02',
      productId: 'prod_02',
      productName: '6 Inch Fly Ash Cement Brick',
      targetQuantity: 12000,
      outputQuantity: 11800,
      damagedQuantity: 200,
      unit: 'Pcs',
      machineLine: 'Semi-Automatic Line 2',
      kilnChamber: 'Curing Bay #4',
      supervisorName: 'Ramesh Patil',
      mixProportion: '1 Part Cement : 4 Parts Fly Ash : 3 Parts Stone Dust : 0.5 Gypsum',
      materialsUsed: [
        { materialId: 'rm_01', materialName: 'Grade 53 OPC Cement', quantity: 48, unit: 'Bags' },
        { materialId: 'rm_02', materialName: 'Thermal Fly Ash', quantity: 11.2, unit: 'Ton' },
        { materialId: 'rm_03', materialName: 'Crushed Stone Dust', quantity: 7.5, unit: 'Ton' },
        { materialId: 'rm_05', materialName: 'Calcined Gypsum Powder', quantity: 6, unit: 'Bags' },
      ],
      workersCount: 12,
      startTime: '07:30 AM',
      endTime: '04:00 PM',
      status: 'curing',
      qualityGrade: 'A Grade',
      remarks: 'Curing water sprinklers activated.',
      createdAt: '2026-09-02T07:30:00Z',
    },
    {
      id: 'batch_03',
      factoryId: 'fact_01',
      batchCode: 'BAT-2026-0893',
      productionDate: '2026-09-02',
      productId: 'prod_04',
      productName: 'Zig-Zag Paver Block 80mm Heavy Duty',
      targetQuantity: 5000,
      outputQuantity: 4900,
      damagedQuantity: 100,
      unit: 'Pcs',
      machineLine: 'Paver Vibro-Compactor Press',
      kilnChamber: 'Paver Stacking Area',
      supervisorName: 'Dinesh Patil',
      mixProportion: 'M40 Design Mix (1:1.5:3 + Iron Oxide Pigment)',
      materialsUsed: [
        { materialId: 'rm_01', materialName: 'Grade 53 OPC Cement', quantity: 35, unit: 'Bags' },
        { materialId: 'rm_03', materialName: 'Crushed Stone Dust', quantity: 8.0, unit: 'Ton' },
        { materialId: 'rm_04', materialName: 'River Washed Sand', quantity: 2.5, unit: 'Brass' },
      ],
      workersCount: 8,
      startTime: '09:00 AM',
      endTime: '06:00 PM',
      status: 'in_progress',
      qualityGrade: 'A Grade',
      remarks: 'Red colour paver top coat running smoothly.',
      createdAt: '2026-09-02T09:00:00Z',
    },
  ],

  stockTransactions: [
    {
      id: 'stk_01',
      factoryId: 'fact_01',
      date: '2026-08-30',
      productId: 'prod_01',
      productName: '4 Inch Fly Ash Cement Brick',
      batchCode: 'BAT-2026-0888',
      transactionType: 'production',
      quantityIn: 15000,
      quantityOut: 0,
      balance: 51250,
      referenceType: 'production_batch',
      notes: 'Batch completion transfer to yard',
      createdBy: 'Dinesh Patil',
      createdAt: '2026-08-30T17:00:00Z',
    },
    {
      id: 'stk_02',
      factoryId: 'fact_01',
      date: '2026-08-31',
      productId: 'prod_01',
      productName: '4 Inch Fly Ash Cement Brick',
      transactionType: 'sale',
      quantityIn: 0,
      quantityOut: 12000,
      balance: 39250,
      referenceType: 'sales_order',
      referenceId: 'so_01',
      notes: 'Dispatch to L&T Construction Site (Truck MH-12-DT-8821)',
      createdBy: 'Sunil Deshmukh',
      createdAt: '2026-08-31T11:30:00Z',
    },
    {
      id: 'stk_03',
      factoryId: 'fact_01',
      date: '2026-09-01',
      productId: 'prod_01',
      productName: '4 Inch Fly Ash Cement Brick',
      batchCode: 'BAT-2026-0891',
      transactionType: 'production',
      quantityIn: 14750,
      quantityOut: 0,
      balance: 54000,
      referenceType: 'production_batch',
      notes: 'Batch BAT-2026-0891 produced',
      createdBy: 'Dinesh Patil',
      createdAt: '2026-09-01T17:30:00Z',
    },
    {
      id: 'stk_04',
      factoryId: 'fact_01',
      date: '2026-09-02',
      productId: 'prod_01',
      productName: '4 Inch Fly Ash Cement Brick',
      transactionType: 'sale',
      quantityIn: 0,
      quantityOut: 5500,
      balance: 48500,
      referenceType: 'sales_order',
      referenceId: 'so_02',
      notes: 'Dispatch to Apex Infra Developers',
      createdBy: 'Sunil Deshmukh',
      createdAt: '2026-09-02T10:15:00Z',
    },
  ],

  employees: [
    {
      id: 'emp_01',
      factoryId: 'fact_01',
      employeeCode: 'EMP-01',
      name: 'Rameshwar Patil',
      phone: '+91 97654 11223',
      address: 'Village Uruli Kanchan, Pune',
      joiningDate: '2024-03-01',
      jobType: 'Supervisor',
      wageType: 'daily',
      dailyWage: 950,
      status: 'active',
      aadharNumber: 'XXXX-XXXX-4812',
      createdAt: '2025-01-16T10:00:00Z',
    },
    {
      id: 'emp_02',
      factoryId: 'fact_01',
      employeeCode: 'EMP-02',
      name: 'Suresh Kumar Sharma',
      phone: '+91 98231 44552',
      address: 'Labour Camp Quarters, Shed 2',
      joiningDate: '2024-05-15',
      jobType: 'Machine Operator',
      wageType: 'daily',
      dailyWage: 750,
      status: 'active',
      createdAt: '2025-01-16T10:00:00Z',
    },
    {
      id: 'emp_03',
      factoryId: 'fact_01',
      employeeCode: 'EMP-03',
      name: 'Santosh Yadav',
      phone: '+91 99755 33211',
      address: 'Labour Camp Quarters, Shed 1',
      joiningDate: '2024-06-01',
      jobType: 'Mould Worker',
      wageType: 'piece_rate',
      dailyWage: 0,
      pieceRatePerThousand: 650, // ₹650 per 1000 bricks made
      status: 'active',
      createdAt: '2025-01-16T10:00:00Z',
    },
    {
      id: 'emp_04',
      factoryId: 'fact_01',
      employeeCode: 'EMP-04',
      name: 'Bharat Shinde',
      phone: '+91 98812 77889',
      address: 'Hadapsar Gaon, Pune',
      joiningDate: '2024-07-10',
      jobType: 'Loader',
      wageType: 'piece_rate',
      dailyWage: 0,
      pieceRatePerThousand: 220, // ₹220 per 1000 bricks loaded into truck
      status: 'active',
      createdAt: '2025-01-16T10:00:00Z',
    },
    {
      id: 'emp_05',
      factoryId: 'fact_01',
      employeeCode: 'EMP-05',
      name: 'Prakash Gawade',
      phone: '+91 94220 99881',
      address: 'Saswad Road, Pune',
      joiningDate: '2024-08-01',
      jobType: 'Driver',
      wageType: 'daily',
      dailyWage: 800,
      status: 'active',
      createdAt: '2025-01-16T10:00:00Z',
    },
    {
      id: 'emp_06',
      factoryId: 'fact_01',
      employeeCode: 'EMP-06',
      name: 'Anil Chauhan',
      phone: '+91 98900 12345',
      address: 'Labour Camp Quarters, Shed 3',
      joiningDate: '2024-09-01',
      jobType: 'Helper',
      wageType: 'daily',
      dailyWage: 550,
      status: 'active',
      createdAt: '2025-01-16T10:00:00Z',
    },
  ],

  attendance: [
    {
      id: 'att_01',
      factoryId: 'fact_01',
      date: '2026-09-02',
      employeeId: 'emp_01',
      employeeName: 'Rameshwar Patil',
      jobType: 'Supervisor',
      status: 'present',
      overtimeHours: 2,
      overtimeAmount: 240,
      dailyWageEarned: 950,
      notes: 'Morning shift & late dispatch monitoring',
      createdAt: '2026-09-02T18:00:00Z',
    },
    {
      id: 'att_02',
      factoryId: 'fact_01',
      date: '2026-09-02',
      employeeId: 'emp_02',
      employeeName: 'Suresh Kumar Sharma',
      jobType: 'Machine Operator',
      status: 'present',
      overtimeHours: 1.5,
      overtimeAmount: 140,
      dailyWageEarned: 750,
      notes: 'Hydraulic press shift completed',
      createdAt: '2026-09-02T18:00:00Z',
    },
    {
      id: 'att_03',
      factoryId: 'fact_01',
      date: '2026-09-02',
      employeeId: 'emp_03',
      employeeName: 'Santosh Yadav',
      jobType: 'Mould Worker',
      status: 'present',
      overtimeHours: 0,
      overtimeAmount: 0,
      unitsProduced: 2500, // 2.5k bricks * ₹650/k = ₹1625
      dailyWageEarned: 1625,
      notes: '2,500 bricks moulded with crew',
      createdAt: '2026-09-02T18:00:00Z',
    },
    {
      id: 'att_04',
      factoryId: 'fact_01',
      date: '2026-09-02',
      employeeId: 'emp_04',
      employeeName: 'Bharat Shinde',
      jobType: 'Loader',
      status: 'present',
      overtimeHours: 0,
      overtimeAmount: 0,
      unitsProduced: 5500, // Loaded 5.5k bricks * ₹220/k = ₹1210
      dailyWageEarned: 1210,
      notes: 'Apex Infra truck loading',
      createdAt: '2026-09-02T18:00:00Z',
    },
    {
      id: 'att_05',
      factoryId: 'fact_01',
      date: '2026-09-02',
      employeeId: 'emp_05',
      employeeName: 'Prakash Gawade',
      jobType: 'Driver',
      status: 'present',
      overtimeHours: 0,
      overtimeAmount: 0,
      dailyWageEarned: 800,
      notes: 'Site delivery round completed',
      createdAt: '2026-09-02T18:00:00Z',
    },
    {
      id: 'att_06',
      factoryId: 'fact_01',
      date: '2026-09-02',
      employeeId: 'emp_06',
      employeeName: 'Anil Chauhan',
      jobType: 'Helper',
      status: 'half_day',
      overtimeHours: 0,
      overtimeAmount: 0,
      dailyWageEarned: 275,
      notes: 'Left at 1:00 PM for medical check',
      createdAt: '2026-09-02T18:00:00Z',
    },
  ],

  wageSlips: [
    {
      id: 'wage_01',
      factoryId: 'fact_01',
      employeeId: 'emp_01',
      employeeName: 'Rameshwar Patil',
      jobType: 'Supervisor',
      period: 'August 2026',
      periodStart: '2026-08-01',
      periodEnd: '2026-08-31',
      presentDays: 26,
      halfDays: 0,
      absentDays: 5,
      dailyWageRate: 950,
      baseWageAmount: 24700,
      overtimeHours: 18,
      overtimeAmount: 2140,
      pieceRateAmount: 0,
      grossAmount: 26840,
      advanceDeduction: 5000,
      otherDeduction: 0,
      netPayable: 21840,
      paidAmount: 21840,
      pendingAmount: 0,
      status: 'paid',
      paymentDate: '2026-09-01',
      paymentMode: 'bank_transfer',
      remarks: 'August full settlement transferred',
      createdAt: '2026-09-01T12:00:00Z',
    },
    {
      id: 'wage_02',
      factoryId: 'fact_01',
      employeeId: 'emp_02',
      employeeName: 'Suresh Kumar Sharma',
      jobType: 'Machine Operator',
      period: 'August 2026',
      periodStart: '2026-08-01',
      periodEnd: '2026-08-31',
      presentDays: 25,
      halfDays: 1,
      absentDays: 5,
      dailyWageRate: 750,
      baseWageAmount: 19125,
      overtimeHours: 12,
      overtimeAmount: 1125,
      pieceRateAmount: 0,
      grossAmount: 20250,
      advanceDeduction: 3000,
      otherDeduction: 0,
      netPayable: 17250,
      paidAmount: 12000,
      pendingAmount: 5250,
      status: 'partial',
      paymentDate: '2026-09-01',
      paymentMode: 'cash',
      remarks: 'Remaining ₹5,250 payable on Saturday',
      createdAt: '2026-09-01T12:00:00Z',
    },
  ],

  customers: [
    {
      id: 'cust_01',
      factoryId: 'fact_01',
      customerName: 'Larsen & Toubro Realty Project',
      companyName: 'L&T Construction Div.',
      phone: '+91 98224 55667',
      whatsapp: '+91 98224 55667',
      email: 'purchase.pune@lntecc.com',
      address: 'Tower C, Commercial Zone, Kharadi',
      city: 'Pune',
      state: 'Maharashtra',
      gstNumber: '27AAACL0149B1Z2',
      creditLimit: 500000,
      openingBalance: 0,
      currentBalance: 87600,
      totalSales: 485000,
      totalPaid: 397400,
      totalPending: 87600,
      status: 'active',
      createdAt: '2025-01-20T10:00:00Z',
    },
    {
      id: 'cust_02',
      factoryId: 'fact_01',
      customerName: 'Apex Infra Developers LLP',
      companyName: 'Apex Infrastructures',
      phone: '+91 98901 88776',
      whatsapp: '+91 98901 88776',
      email: 'apexinfra.pune@gmail.com',
      address: 'Apex Heights, Baner Road',
      city: 'Pune',
      state: 'Maharashtra',
      gstNumber: '27AAKFA7812C1ZT',
      creditLimit: 200000,
      openingBalance: 15000,
      currentBalance: 42350,
      totalSales: 215000,
      totalPaid: 172650,
      totalPending: 42350,
      status: 'active',
      createdAt: '2025-02-10T10:00:00Z',
    },
    {
      id: 'cust_03',
      factoryId: 'fact_01',
      customerName: 'Modern Builders & Contractors',
      companyName: 'Modern Builders',
      phone: '+91 94225 33445',
      whatsapp: '+91 94225 33445',
      email: 'modernbuilders.mh@gmail.com',
      address: 'Ganesh Plaza, Wagholi',
      city: 'Pune',
      state: 'Maharashtra',
      gstNumber: '27AAFFM4491D1Z5',
      creditLimit: 150000,
      openingBalance: 0,
      currentBalance: 0,
      totalSales: 168000,
      totalPaid: 168000,
      totalPending: 0,
      status: 'active',
      createdAt: '2025-03-01T10:00:00Z',
    },
    {
      id: 'cust_04',
      factoryId: 'fact_01',
      customerName: 'Balaji Building Material Suppliers',
      companyName: 'Balaji Traders',
      phone: '+91 98230 66778',
      whatsapp: '+91 98230 66778',
      email: 'balaji.traders.pune@yahoo.com',
      address: 'Near Old Toll Gate, Saswad',
      city: 'Pune',
      state: 'Maharashtra',
      creditLimit: 100000,
      openingBalance: 8000,
      currentBalance: 31200,
      totalSales: 142000,
      totalPaid: 110800,
      totalPending: 31200,
      status: 'active',
      createdAt: '2025-04-12T10:00:00Z',
    },
  ],

  vendors: [
    {
      id: 'ven_01',
      factoryId: 'fact_01',
      vendorName: 'UltraTech Cement Authorized Depot',
      company: 'UltraTech Cement Ltd (Deccan Agency)',
      phone: '+91 98221 00112',
      whatsapp: '+91 98221 00112',
      email: 'sales.deccan@ultratechcement.com',
      address: 'Railway Siding Yard, Ghorpadi',
      city: 'Pune',
      state: 'Maharashtra',
      gstNumber: '27AAACU1234F1Z8',
      materialsSupplied: ['Grade 53 OPC Cement (UltraTech / ACC)'],
      openingBalance: 0,
      currentBalance: 33500,
      totalPurchases: 1449000,
      totalPaid: 1415500,
      totalPending: 33500,
      status: 'active',
      createdAt: '2025-01-16T10:00:00Z',
    },
    {
      id: 'ven_02',
      factoryId: 'fact_01',
      vendorName: 'Maha Thermal Ash Logistics',
      company: 'Maha Ash Bulk Carriers Pvt Ltd',
      phone: '+91 99230 44556',
      whatsapp: '+91 99230 44556',
      email: 'dispatch@mahathermalash.in',
      address: 'Plot 18, TPS Colony, Parli Vaijnath',
      city: 'Beed',
      state: 'Maharashtra',
      gstNumber: '27AABCM6612N1Z3',
      materialsSupplied: ['Thermal Fly Ash (Grade F dry powder)'],
      openingBalance: 0,
      currentBalance: 0,
      totalPurchases: 578000,
      totalPaid: 578000,
      totalPending: 0,
      status: 'active',
      createdAt: '2025-01-16T10:00:00Z',
    },
    {
      id: 'ven_03',
      factoryId: 'fact_01',
      vendorName: 'Shree Krishna Stone Crushers',
      company: 'Krishna Mineral Processing Works',
      phone: '+91 98810 33221',
      whatsapp: '+91 98810 33221',
      email: 'krishna.crushers@gmail.com',
      address: 'Quarry Zone #4, Theur Phata',
      city: 'Pune',
      state: 'Maharashtra',
      gstNumber: '27AAHPK9918M1ZF',
      materialsSupplied: ['Crushed Stone Dust (0-4mm aggregate)', 'River Washed Sand (M-Sand)'],
      openingBalance: 0,
      currentBalance: 14400,
      totalPurchases: 628000,
      totalPaid: 613600,
      totalPending: 14400,
      status: 'active',
      createdAt: '2025-01-16T10:00:00Z',
    },
    {
      id: 'ven_04',
      factoryId: 'fact_01',
      vendorName: 'Western Coal Logistics & Fuels',
      company: 'Western Coal Carriers',
      phone: '+91 94220 77112',
      whatsapp: '+91 94220 77112',
      email: 'westerncoal.mh@yahoo.com',
      address: 'Coal Depot Road, Chandrapur',
      city: 'Chandrapur',
      state: 'Maharashtra',
      gstNumber: '27AACFW3321A1ZB',
      materialsSupplied: ['High CV Boiler Coal (Kiln Fuel)'],
      openingBalance: 0,
      currentBalance: 45000,
      totalPurchases: 864000,
      totalPaid: 819000,
      totalPending: 45000,
      status: 'active',
      createdAt: '2025-01-16T10:00:00Z',
    },
  ],

  saleOrders: [
    {
      id: 'so_01',
      factoryId: 'fact_01',
      invoiceNumber: 'INV-2026-0418',
      saleDate: '2026-08-31',
      customerId: 'cust_01',
      customerName: 'Larsen & Toubro Realty Project',
      customerPhone: '+91 98224 55667',
      customerGst: '27AAACL0149B1Z2',
      items: [
        {
          productId: 'prod_01',
          productName: '4 Inch Fly Ash Cement Brick',
          hsnCode: '681599',
          batchCode: 'BAT-2026-0888',
          quantity: 12000,
          unit: 'Pcs',
          rate: 4.80,
          discount: 0,
          taxPercent: 12,
          amount: 57600,
        },
      ],
      subtotal: 57600,
      discountTotal: 0,
      taxTotal: 6912,
      grandTotal: 64512,
      paidAmount: 0,
      pendingAmount: 64512,
      paymentStatus: 'pending',
      deliveryDetails: {
        vehicleNumber: 'MH-12-DT-8821',
        driverName: 'Ramdas Mane',
        driverPhone: '+91 98223 99881',
        destinationAddress: 'L&T Raintree Boulevard Site, Kharadi, Pune',
        freightCharges: 3500,
        freightPaidBy: 'customer',
      },
      notes: 'PO Ref: LT/KHD/2026/08/991',
      createdAt: '2026-08-31T11:00:00Z',
    },
    {
      id: 'so_02',
      factoryId: 'fact_01',
      invoiceNumber: 'INV-2026-0419',
      saleDate: '2026-09-02',
      customerId: 'cust_02',
      customerName: 'Apex Infra Developers LLP',
      customerPhone: '+91 98901 88776',
      customerGst: '27AAKFA7812C1ZT',
      items: [
        {
          productId: 'prod_01',
          productName: '4 Inch Fly Ash Cement Brick',
          hsnCode: '681599',
          batchCode: 'BAT-2026-0891',
          quantity: 5500,
          unit: 'Pcs',
          rate: 4.80,
          discount: 0,
          taxPercent: 12,
          amount: 26400,
        },
      ],
      subtotal: 26400,
      discountTotal: 0,
      taxTotal: 3168,
      grandTotal: 29568,
      paidAmount: 15000,
      pendingAmount: 14568,
      paymentStatus: 'partial',
      deliveryDetails: {
        vehicleNumber: 'MH-12-AB-5541',
        driverName: 'Prakash Gawade',
        destinationAddress: 'Apex Heights Site, Baner, Pune',
      },
      notes: 'Partial advance received ₹15,000 via UPI',
      createdAt: '2026-09-02T10:00:00Z',
    },
  ],

  invoices: [
    {
      id: 'inv_01',
      factoryId: 'fact_01',
      invoiceNumber: 'INV-2026-0418',
      saleOrderId: 'so_01',
      invoiceDate: '2026-08-31',
      dueDate: '2026-09-15',
      customer: {
        id: 'cust_01',
        name: 'Larsen & Toubro Realty Project',
        company: 'L&T Construction Div.',
        phone: '+91 98224 55667',
        email: 'purchase.pune@lntecc.com',
        address: 'Tower C, Commercial Zone, Kharadi, Pune, MH - 411014',
        gstNumber: '27AAACL0149B1Z2',
      },
      items: [
        {
          productId: 'prod_01',
          name: '4 Inch Fly Ash Cement Brick (9x4x3)',
          hsnCode: '681599',
          quantity: 12000,
          unit: 'Pcs',
          rate: 4.80,
          amount: 57600,
          discount: 0,
          taxRate: 12,
          taxAmount: 6912,
          total: 64512,
        },
      ],
      subtotal: 57600,
      discount: 0,
      taxableAmount: 57600,
      cgst: 3456,
      sgst: 3456,
      igst: 0,
      grandTotal: 64512,
      paidAmount: 0,
      pendingAmount: 64512,
      status: 'pending',
      termsAndConditions: [
        'Payment terms: 15 days credit period.',
        'Goods once sold will not be taken back or exchanged.',
        'Unloading breakage tolerance is up to 2% standard industry norms.',
        'Interest @ 18% p.a. will be charged on overdue payments beyond due date.',
      ],
      vehicleNumber: 'MH-12-DT-8821',
      eWayBillNumber: '281099281726',
      createdAt: '2026-08-31T11:00:00Z',
    },
    {
      id: 'inv_02',
      factoryId: 'fact_01',
      invoiceNumber: 'INV-2026-0419',
      saleOrderId: 'so_02',
      invoiceDate: '2026-09-02',
      dueDate: '2026-09-09',
      customer: {
        id: 'cust_02',
        name: 'Apex Infra Developers LLP',
        company: 'Apex Infrastructures',
        phone: '+91 98901 88776',
        email: 'apexinfra.pune@gmail.com',
        address: 'Apex Heights, Baner Road, Pune, MH - 411045',
        gstNumber: '27AAKFA7812C1ZT',
      },
      items: [
        {
          productId: 'prod_01',
          name: '4 Inch Fly Ash Cement Brick (9x4x3)',
          hsnCode: '681599',
          quantity: 5500,
          unit: 'Pcs',
          rate: 4.80,
          amount: 26400,
          discount: 0,
          taxRate: 12,
          taxAmount: 3168,
          total: 29568,
        },
      ],
      subtotal: 26400,
      discount: 0,
      taxableAmount: 26400,
      cgst: 1584,
      sgst: 1584,
      igst: 0,
      grandTotal: 29568,
      paidAmount: 15000,
      pendingAmount: 14568,
      status: 'partial',
      termsAndConditions: [
        'Goods inspected and verified at time of dispatch.',
        'Payment terms: Net 7 Days.',
      ],
      vehicleNumber: 'MH-12-AB-5541',
      createdAt: '2026-09-02T10:00:00Z',
    },
  ],

  expenses: [
    {
      id: 'exp_01',
      factoryId: 'fact_01',
      date: '2026-08-29',
      category: 'Diesel',
      description: 'Diesel 120 Litres for 125 KVA Kirloskar Generator',
      amount: 11400,
      paymentMode: 'upi',
      paidBy: 'Rajesh Sharma',
      reference: 'IOCL Pump Wagholi Txn #88912',
      recipientName: 'Indian Oil Dealer Wagholi',
      createdAt: '2026-08-29T18:00:00Z',
    },
    {
      id: 'exp_02',
      factoryId: 'fact_01',
      date: '2026-08-30',
      category: 'Machine Repair',
      description: 'Hydraulic Cylinder Seal replacement & hydraulic oil top-up (Line 1)',
      amount: 8500,
      paymentMode: 'cash',
      paidBy: 'Dinesh Patil',
      recipientName: 'Shree Sai Hydraulic Works',
      createdAt: '2026-08-30T19:30:00Z',
    },
    {
      id: 'exp_03',
      factoryId: 'fact_01',
      date: '2026-09-01',
      category: 'Electricity',
      description: 'MSEDCL Industrial HT Power Bill for August 2026',
      amount: 48500,
      paymentMode: 'bank_transfer',
      paidBy: 'Rajesh Sharma',
      reference: 'MSEDCL Consumer #018892019',
      recipientName: 'Maharashtra State Electricity Distribution Co.',
      createdAt: '2026-09-01T15:00:00Z',
    },
    {
      id: 'exp_04',
      factoryId: 'fact_01',
      date: '2026-09-02',
      category: 'Food',
      description: 'Worker Morning & Evening Tea and Biscuits (Weekly canteen tally)',
      amount: 1650,
      paymentMode: 'cash',
      paidBy: 'Dinesh Patil',
      recipientName: 'Pandurang Canteen',
      createdAt: '2026-09-02T17:00:00Z',
    },
  ],

  payments: [
    {
      id: 'pay_01',
      factoryId: 'fact_01',
      date: '2026-08-31',
      partyType: 'customer',
      partyId: 'cust_01',
      partyName: 'Larsen & Toubro Realty Project',
      paymentType: 'receipt',
      amount: 150000,
      paymentMode: 'neft_rtgs',
      reference: 'NEFT UTR: HDFCN26243891001',
      invoiceRef: 'INV-2026-0395',
      notes: 'Cleared part balance of previous project phase',
      createdAt: '2026-08-31T14:00:00Z',
    },
    {
      id: 'pay_02',
      factoryId: 'fact_01',
      date: '2026-09-01',
      partyType: 'vendor',
      partyId: 'ven_01',
      partyName: 'UltraTech Cement Authorized Depot',
      paymentType: 'payment',
      amount: 70000,
      paymentMode: 'bank_transfer',
      reference: 'Txn Ref: TRF98910283',
      invoiceRef: 'UT-9921',
      notes: 'Cement invoice purchase installment',
      createdAt: '2026-09-01T16:00:00Z',
    },
    {
      id: 'pay_03',
      factoryId: 'fact_01',
      date: '2026-09-01',
      partyType: 'labour',
      partyId: 'emp_01',
      partyName: 'Rameshwar Patil (Supervisor)',
      paymentType: 'payment',
      amount: 21840,
      paymentMode: 'bank_transfer',
      reference: 'UPI: rameshwar@oksbi',
      notes: 'August 2026 wage settlement',
      createdAt: '2026-09-01T17:00:00Z',
    },
    {
      id: 'pay_04',
      factoryId: 'fact_01',
      date: '2026-09-02',
      partyType: 'customer',
      partyId: 'cust_02',
      partyName: 'Apex Infra Developers LLP',
      paymentType: 'receipt',
      amount: 15000,
      paymentMode: 'upi',
      reference: 'UPI Ref: 424590192831',
      invoiceRef: 'INV-2026-0419',
      notes: 'Advance against dispatch #INV-2026-0419',
      createdAt: '2026-09-02T10:30:00Z',
    },
  ],

  notifications: [
    {
      id: 'notif_01',
      factoryId: 'fact_01',
      title: 'Low Raw Material Stock Warning',
      message: 'Calcined Gypsum Powder is at 22 Bags (Minimum threshold is 30 Bags). Reorder recommended.',
      type: 'low_stock',
      severity: 'warning',
      link: '/raw-materials',
      isRead: false,
      createdAt: '2026-09-02T08:15:00Z',
    },
    {
      id: 'notif_02',
      factoryId: 'fact_01',
      title: 'Customer Payment Overdue',
      message: 'L&T Realty Project has invoice INV-2026-0418 of ₹64,512 due for payment.',
      type: 'payment_due',
      severity: 'info',
      link: '/invoices',
      isRead: false,
      createdAt: '2026-09-02T09:00:00Z',
    },
    {
      id: 'notif_03',
      factoryId: 'fact_01',
      title: 'Production Batch Curing Alert',
      message: 'Batch BAT-2026-0892 (6 Inch Fly Ash Brick) has completed 24h water curing cycle.',
      type: 'production',
      severity: 'success',
      link: '/production',
      isRead: true,
      createdAt: '2026-09-02T11:00:00Z',
    },
    {
      id: 'notif_04',
      factoryId: 'fact_01',
      title: 'Pending Labour Wage Settlement',
      message: 'Suresh Kumar Sharma has ₹5,250 pending wage balance from August.',
      type: 'wages_pending',
      severity: 'warning',
      link: '/labour',
      isRead: false,
      createdAt: '2026-09-02T13:30:00Z',
    },
  ],

  auditLogs: [
    {
      id: 'aud_01',
      factoryId: 'fact_01',
      userId: 'usr_owner',
      userName: 'Rajesh Sharma',
      userRole: 'factory_owner',
      module: 'Production',
      action: 'CREATE',
      recordId: 'BAT-2026-0891',
      recordTitle: 'Batch BAT-2026-0891 (4" Fly Ash Brick)',
      details: 'Recorded production output of 14,750 Pcs. Automatically consumed 42 bags Cement and 9.5 Ton Fly Ash.',
      timestamp: '2026-09-01T17:30:00Z',
    },
    {
      id: 'aud_02',
      factoryId: 'fact_01',
      userId: 'usr_owner',
      userName: 'Rajesh Patel',
      userRole: 'factory_owner',
      module: 'Sales & Invoicing',
      action: 'CREATE',
      recordId: 'INV-2026-0419',
      recordTitle: 'Tax Invoice INV-2026-0419 for Apex Infra Developers',
      details: 'Generated GST Tax Invoice for 5,500 Pcs 4" Fly Ash Brick. Deducted 5,500 Pcs from finished stock.',
      timestamp: '2026-09-02T10:00:00Z',
    },
    {
      id: 'aud_03',
      factoryId: 'fact_01',
      userId: 'usr_owner',
      userName: 'Rajesh Patel',
      userRole: 'factory_owner',
      module: 'Labour Attendance',
      action: 'UPDATE',
      recordId: 'ATT-2026-09-02',
      recordTitle: 'Daily Attendance Roster for 6 Workers',
      details: 'Marked daily muster: 5 Present, 1 Half Day, 3.5 hrs Overtime.',
      timestamp: '2026-09-02T18:00:00Z',
    },
  ],
};

class DatabaseStore {
  private db: DatabaseSchema;
  private listeners: Set<() => void> = new Set();

  constructor() {
    this.db = this.loadFromStorage();
  }

  private loadFromStorage(): DatabaseSchema {
    try {
      const stored = localStorage.getItem(STORAGE_KEY);
      if (stored) {
        const parsed = JSON.parse(stored);
        return {
          ...SEED_DATA,
          ...parsed,
        };
      }
    } catch (e) {
      console.error('Error loading DB from storage:', e);
    }
    return JSON.parse(JSON.stringify(SEED_DATA));
  }

  private saveToStorage(): void {
    try {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(this.db));
      this.notifyListeners();
    } catch (e) {
      console.error('Error saving DB to storage:', e);
    }
  }

  public subscribe(listener: () => void): () => void {
    this.listeners.add(listener);
    return () => {
      this.listeners.delete(listener);
    };
  }

  private notifyListeners(): void {
    this.listeners.forEach(fn => fn());
  }

  public resetToDefault(): void {
    this.db = JSON.parse(JSON.stringify(SEED_DATA));
    this.saveToStorage();
  }

  public reset(): void {
    this.resetToDefault();
  }

  public exportJSON(): string {
    return JSON.stringify(this.db, null, 2);
  }

  public importJSON(jsonString: string): boolean {
    try {
      const parsed = JSON.parse(jsonString);
      this.db = parsed;
      this.saveToStorage();
      return true;
    } catch (e) {
      console.error(e);
      return false;
    }
  }

  public get<K extends keyof DatabaseSchema>(key: K): DatabaseSchema[K] {
    return this.db[key];
  }

  public set<K extends keyof DatabaseSchema>(key: K, data: DatabaseSchema[K]): void {
    this.db[key] = data;
    this.saveToStorage();
  }

  // Helper mutation functions with relational cascades
  public addAuditLog(
    factoryId: string, 
    userId: string, 
    userName: string, 
    userRole: any, 
    module: string, 
    action: any, 
    recordId: string, 
    recordTitle: string, 
    details: string
  ): void {
    const log: AuditLogItem = {
      id: generateId('aud'),
      factoryId,
      userId,
      userName,
      userRole,
      module,
      action,
      recordId,
      recordTitle,
      details,
      timestamp: new Date().toISOString(),
    };
    this.db.auditLogs.unshift(log);
    this.saveToStorage();
  }
}

export const dbStore = new DatabaseStore();
